---
title: "Awards"
editor: visual
---

## **2026**

Winner of ***The Jenei Award,*** awarded for **"a remarkable and commendable contribution to an innovative or under researched field in public management"** (named after Gyogy Jenei) by *Public Management Review*, *Taylor & Francis* and *IRSPM 2026*. Shared with *Simon Teasdale (QUB)* <a href="https://www.tandfonline.com/journals/rpxm20/collections/jenei-award" target="_blank" rel="noopener" style="white-space: nowrap; text-decoration: none;"> 🌟 [Award]{style="background-color: #e8f0fe; padding: 0.1rem 0.3rem; border-radius: 0.25rem;"} </a>

***Stanford 2% Scientist (2025, 2024, 2023, 2022, 2021),*** for two categories: **Public Administration and Political Science** and **Business and Management** <a href="https://elsevier.digitalcommonsdata.com/datasets/btchxktzyw/8" target="_blank" rel="noopener" style="white-space: nowrap; text-decoration: none;">🗂️️ 2025 Data</a>

## **2024**

Winner of ***Best Conference Proceeding Paper,*** **The Annual Academy of Management Meeting 2024** ***"Finetuning Artificial Intelligence for Entrepreneurial Pitching Effectiveness"*** Awarded by *The Academy of Management*, *Technology and Innovation Management Division.* Shared with *Stratos Ramoglou (Bristol) and Shang Liang (EduUHK)*

## **2022**

Winner of ***The Kooiman Best Paper Award 2021*** recognizing his contribution to public management research. Shared with Liang Shang (EduUHK) & Michael Roy (Stirling) <a href="https://www.tandfonline.com/journals/rpxm20/collections/best-paper-kooiman-prize" target="_blank" rel="noopener" style="white-space: nowrap; text-decoration: none;"> 🌟 [Award]{style="background-color: #e8f0fe; padding: 0.1rem 0.3rem; border-radius: 0.25rem;"} </a>

Winner of ***Best Conference Proceeding Paper,*** **The Annual Academy of Management Meeting 2022** ***The Mechanisms of Performance in Social Entrepreneurship: Assemblage, Market Building, Issue Selling*** Awarded by the Academy of Management 2022, Entrepreneurship Division. Shared with *Long Wang (CityUHK)*

## **2021**

Winner of ***Best Paper Award*** **International Social Innovation Research Conference (ISIRC) 2020**, Sheffield, United Kingdom. ***"Understanding Healthcare Social Enterprises: A New Public Governance Perspective."*** Shared with *Shang Liang (EduHK) and Michael Roy (Stirling)* Published in **Journal of Social Policy** <a href="https://doi.org/10.1017/S0047279421000222" target="_blank" rel="noopener" style="white-space: nowrap; text-decoration: none;"> 🌟 [Award]{style="background-color: #e8f0fe; padding: 0.1rem 0.3rem; border-radius: 0.25rem;"} </a>

Winner of ***Editors' Choice Award 2021***, 2021管理觀念與應用研討會編輯特選獎, 國立台灣大學管理學院，國立中山大學管理學院. Awarded by National Taiwan University and National Sun Yat Sen University (Taiwan). Shared with *Shu-Jung Yang (York)*

## **2017**

Winner of ***Teaching Innovation Award 2017,*** awarded by the College of Liberal Arts and Social Sciences (CLASS), City University of Hong Kong. <a href="https://www.cityu.edu.hk/class/media_events/news_item.aspx?ref=110" target="_blank" rel="noopener" style="white-space: nowrap; text-decoration: none;"> ✨ [Award]{style="background-color: #f0e6d2; padding: 0.1rem 0.3rem; border-radius: 0.25rem;"} </a>

## **2016**

Winner of  ***Teaching Excellence 2015 Award,*** a university-wide contest, awarded by the President of City University of Hong Kong. <a href="https://www.cityu.edu.hk/tea/awardee/tea/index.htm" target="_blank" rel="noopener" style="white-space: nowrap; text-decoration: none;"> ✨ [Award]{style="background-color: #f0e6d2; padding: 0.1rem 0.3rem; border-radius: 0.25rem;"} </a>

 ***Finalist of UGC Teaching Excellence Award 2016,*** a nominee representing City University of Hong Kong at the UGC level selection.